# Lazygit config for Antigravity
# Usage: lazygit -ucf ~/.config/lazygit/config-antigravity.yml

os:
  edit: "antigravity {{filename}}"
  editAtLine: "antigravity --goto {{filename}}:{{line}}"

promptToReturnFromSubprocess: false

gui:
  nerdFontsVersion: "3"
  # Automatically increases the height of the focused side panel
  expandFocusedSidePanel: true
  # Determines how much taller the focused panel is compared to others
  expandedSidePanelWeight: 2
  # default is 0.3333
  sidePanelWidth: 0.25

git:
  pagers:
    - pager: delta --dark --paging=never
      colorArg: always

keybinding:
  universal:
    prevItem: "k"
    nextItem: "j"
    prevBlock: "<up>"
    nextBlock: "<down>"
    prevTab: "<left>"
    nextTab: "<right>"
    gotoTop-alt: "" # This will unbind 'home'
    gotoBottom-alt: "" # This will unbind 'end'
    prevPage: "<home>" # With my keyboard layout, home is equivalent to 'page up'
    nextPage: "<end>" # With my keyboard layout, end is equivalent to 'page down'
    extrasMenu: "9" # I like to use '9' as the extras
    goInto: "I" # I like to use 'I' instead of 'Enter' to go into a file, a commit, etc
